spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.restaurant.entity,com.example.restaurant.dto
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
